### ISSUE TITLE
使用text-embedding-ada-002新模型报错

### ISSUE THREAD

**Issue by InternetBugs** [Soulter/QQChannelChatGPT#6]
根据openai官方介绍，text-embedding-ada-002拥有更强的性能和更低的价格https://openai.com/blog/new-and-improved-embedding-model/
不过使用这个模型会报错，详情见图
![Screenshot_20221216-060605_QQ](https://user-images.githubusercontent.com/77239633/207977666-9959a84f-dfce-4c18-9436-9d9baeaeb5b1.png)

**Comment by InternetBugs** [comment]
配置文件内是这样的
```
openai:
  key: 
  chatGPTConfigs:
    engine: text-embedding-ada-002
    max_tokens: 1024
    temperature: 0.9
    top_p: 1
    frequency_penalty: 0.4
    presence_penalty: 0.3
  total_tokens_limit: 5000


qqbot:
  appid: 
  token: 

# 设置是否一个人一个会话
uniqueSessionMode: false

# QChannelBot 的版本
version: 1.4
```
